#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LapTrinhWeb_QuanLyBanXe.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanXe-20221230012255")]
	public partial class An_1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertChiTietPhieuBan(ChiTietPhieuBan instance);
    partial void UpdateChiTietPhieuBan(ChiTietPhieuBan instance);
    partial void DeleteChiTietPhieuBan(ChiTietPhieuBan instance);
    partial void InsertChiTietXe(ChiTietXe instance);
    partial void UpdateChiTietXe(ChiTietXe instance);
    partial void DeleteChiTietXe(ChiTietXe instance);
    partial void InsertHangXe(HangXe instance);
    partial void UpdateHangXe(HangXe instance);
    partial void DeleteHangXe(HangXe instance);
    partial void InsertHinhAnh(HinhAnh instance);
    partial void UpdateHinhAnh(HinhAnh instance);
    partial void DeleteHinhAnh(HinhAnh instance);
    partial void InsertHinhThucThanhToan(HinhThucThanhToan instance);
    partial void UpdateHinhThucThanhToan(HinhThucThanhToan instance);
    partial void DeleteHinhThucThanhToan(HinhThucThanhToan instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKhachHangThanThiet(KhachHangThanThiet instance);
    partial void UpdateKhachHangThanThiet(KhachHangThanThiet instance);
    partial void DeleteKhachHangThanThiet(KhachHangThanThiet instance);
    partial void InsertLoaiAcc(LoaiAcc instance);
    partial void UpdateLoaiAcc(LoaiAcc instance);
    partial void DeleteLoaiAcc(LoaiAcc instance);
    partial void InsertLoaiHinhAnh(LoaiHinhAnh instance);
    partial void UpdateLoaiHinhAnh(LoaiHinhAnh instance);
    partial void DeleteLoaiHinhAnh(LoaiHinhAnh instance);
    partial void InsertLoaiKhachHang(LoaiKhachHang instance);
    partial void UpdateLoaiKhachHang(LoaiKhachHang instance);
    partial void DeleteLoaiKhachHang(LoaiKhachHang instance);
    partial void InsertLoaiXe(LoaiXe instance);
    partial void UpdateLoaiXe(LoaiXe instance);
    partial void DeleteLoaiXe(LoaiXe instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhanXet(NhanXet instance);
    partial void UpdateNhanXet(NhanXet instance);
    partial void DeleteNhanXet(NhanXet instance);
    partial void InsertPhieuBanHang(PhieuBanHang instance);
    partial void UpdatePhieuBanHang(PhieuBanHang instance);
    partial void DeletePhieuBanHang(PhieuBanHang instance);
    #endregion
		
		public An_1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyBanXe_20221230012255ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public An_1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public An_1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public An_1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public An_1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuBan> ChiTietPhieuBans
		{
			get
			{
				return this.GetTable<ChiTietPhieuBan>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietXe> ChiTietXes
		{
			get
			{
				return this.GetTable<ChiTietXe>();
			}
		}
		
		public System.Data.Linq.Table<HangXe> HangXes
		{
			get
			{
				return this.GetTable<HangXe>();
			}
		}
		
		public System.Data.Linq.Table<HinhAnh> HinhAnhs
		{
			get
			{
				return this.GetTable<HinhAnh>();
			}
		}
		
		public System.Data.Linq.Table<HinhThucThanhToan> HinhThucThanhToans
		{
			get
			{
				return this.GetTable<HinhThucThanhToan>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<KhachHangThanThiet> KhachHangThanThiets
		{
			get
			{
				return this.GetTable<KhachHangThanThiet>();
			}
		}
		
		public System.Data.Linq.Table<LoaiAcc> LoaiAccs
		{
			get
			{
				return this.GetTable<LoaiAcc>();
			}
		}
		
		public System.Data.Linq.Table<LoaiHinhAnh> LoaiHinhAnhs
		{
			get
			{
				return this.GetTable<LoaiHinhAnh>();
			}
		}
		
		public System.Data.Linq.Table<LoaiKhachHang> LoaiKhachHangs
		{
			get
			{
				return this.GetTable<LoaiKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiXe> LoaiXes
		{
			get
			{
				return this.GetTable<LoaiXe>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhanXet> NhanXets
		{
			get
			{
				return this.GetTable<NhanXet>();
			}
		}
		
		public System.Data.Linq.Table<PhieuBanHang> PhieuBanHangs
		{
			get
			{
				return this.GetTable<PhieuBanHang>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_ChiTietPhieuBan")]
		public int Insert_ChiTietPhieuBan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_PhieuBan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaXe", DbType="VarChar(5)")] string maXe, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SoLuong", DbType="Int")] System.Nullable<int> soLuong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_PhieuBan, maXe, soLuong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Xoa_1Xe")]
		public int Xoa_1Xe([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaXe", DbType="VarChar(5)")] string maXe)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maXe);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insert_PhieuBanHang")]
		public int Insert_PhieuBanHang([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKhachHang", DbType="VarChar(5)")] string maKhachHang, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HT_ThanhToan", DbType="Int")] System.Nullable<int> hT_ThanhToan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKhachHang, hT_ThanhToan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LocHoaDonQuaHan")]
		public int LocHoaDonQuaHan()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GiamGia", IsComposable=true)]
		public System.Nullable<int> GiamGia([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaKH", DbType="VarChar(5)")] string maKH)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.KiemTra_KH_ThanThiet", IsComposable=true)]
		public string KiemTra_KH_ThanThiet([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(5)")] string maKH)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maKH).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accounts")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private int _LoaiAcc;
		
		private string _MatKhau;
		
		private EntitySet<KhachHang> _KhachHangs;
		
		private EntitySet<NhanVien> _NhanViens;
		
		private EntityRef<LoaiAcc> _LoaiAcc1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnLoaiAccChanging(int value);
    partial void OnLoaiAccChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public Account()
		{
			this._KhachHangs = new EntitySet<KhachHang>(new Action<KhachHang>(this.attach_KhachHangs), new Action<KhachHang>(this.detach_KhachHangs));
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			this._LoaiAcc1 = default(EntityRef<LoaiAcc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiAcc", DbType="Int NOT NULL")]
		public int LoaiAcc
		{
			get
			{
				return this._LoaiAcc;
			}
			set
			{
				if ((this._LoaiAcc != value))
				{
					if (this._LoaiAcc1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiAccChanging(value);
					this.SendPropertyChanging();
					this._LoaiAcc = value;
					this.SendPropertyChanged("LoaiAcc");
					this.OnLoaiAccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(30)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_KhachHang", Storage="_KhachHangs", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<KhachHang> KhachHangs
		{
			get
			{
				return this._KhachHangs;
			}
			set
			{
				this._KhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_NhanVien", Storage="_NhanViens", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiAcc_Account", Storage="_LoaiAcc1", ThisKey="LoaiAcc", OtherKey="id", IsForeignKey=true)]
		public LoaiAcc LoaiAcc1
		{
			get
			{
				return this._LoaiAcc1.Entity;
			}
			set
			{
				LoaiAcc previousValue = this._LoaiAcc1.Entity;
				if (((previousValue != value) 
							|| (this._LoaiAcc1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiAcc1.Entity = null;
						previousValue.Accounts.Remove(this);
					}
					this._LoaiAcc1.Entity = value;
					if ((value != null))
					{
						value.Accounts.Add(this);
						this._LoaiAcc = value.id;
					}
					else
					{
						this._LoaiAcc = default(int);
					}
					this.SendPropertyChanged("LoaiAcc1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_KhachHangs(KhachHang entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Account = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.Account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaXe;
		
		private System.Nullable<int> _MaLoaiXe;
		
		private string _MaNSX;
		
		private string _TenXe;
		
		private string _AnhBia;
		
		private string _MoTa;
		
		private System.Nullable<double> _Gia;
		
		private System.Nullable<int> _SoLuong;
		
		private EntitySet<ChiTietPhieuBan> _ChiTietPhieuBans;
		
		private EntityRef<ChiTietXe> _ChiTietXe;
		
		private EntitySet<HinhAnh> _HinhAnhs;
		
		private EntitySet<NhanXet> _NhanXets;
		
		private EntityRef<HangXe> _HangXe;
		
		private EntityRef<LoaiXe> _LoaiXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnMaLoaiXeChanging(System.Nullable<int> value);
    partial void OnMaLoaiXeChanged();
    partial void OnMaNSXChanging(string value);
    partial void OnMaNSXChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public Xe()
		{
			this._ChiTietPhieuBans = new EntitySet<ChiTietPhieuBan>(new Action<ChiTietPhieuBan>(this.attach_ChiTietPhieuBans), new Action<ChiTietPhieuBan>(this.detach_ChiTietPhieuBans));
			this._ChiTietXe = default(EntityRef<ChiTietXe>);
			this._HinhAnhs = new EntitySet<HinhAnh>(new Action<HinhAnh>(this.attach_HinhAnhs), new Action<HinhAnh>(this.detach_HinhAnhs));
			this._NhanXets = new EntitySet<NhanXet>(new Action<NhanXet>(this.attach_NhanXets), new Action<NhanXet>(this.detach_NhanXets));
			this._HangXe = default(EntityRef<HangXe>);
			this._LoaiXe = default(EntityRef<LoaiXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiXe", DbType="Int")]
		public System.Nullable<int> MaLoaiXe
		{
			get
			{
				return this._MaLoaiXe;
			}
			set
			{
				if ((this._MaLoaiXe != value))
				{
					if (this._LoaiXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiXe = value;
					this.SendPropertyChanged("MaLoaiXe");
					this.OnMaLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSX", DbType="VarChar(5)")]
		public string MaNSX
		{
			get
			{
				return this._MaNSX;
			}
			set
			{
				if ((this._MaNSX != value))
				{
					if (this._HangXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNSXChanging(value);
					this.SendPropertyChanging();
					this._MaNSX = value;
					this.SendPropertyChanged("MaNSX");
					this.OnMaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(50)")]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(30)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_ChiTietPhieuBan", Storage="_ChiTietPhieuBans", ThisKey="MaXe", OtherKey="MaXe")]
		public EntitySet<ChiTietPhieuBan> ChiTietPhieuBans
		{
			get
			{
				return this._ChiTietPhieuBans;
			}
			set
			{
				this._ChiTietPhieuBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_ChiTietXe", Storage="_ChiTietXe", ThisKey="MaXe", OtherKey="id_ChiTietXe", IsUnique=true, IsForeignKey=false)]
		public ChiTietXe ChiTietXe
		{
			get
			{
				return this._ChiTietXe.Entity;
			}
			set
			{
				ChiTietXe previousValue = this._ChiTietXe.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietXe.Entity = null;
						previousValue.Xe = null;
					}
					this._ChiTietXe.Entity = value;
					if ((value != null))
					{
						value.Xe = this;
					}
					this.SendPropertyChanged("ChiTietXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_HinhAnh", Storage="_HinhAnhs", ThisKey="MaXe", OtherKey="Id_DanhMucHinh")]
		public EntitySet<HinhAnh> HinhAnhs
		{
			get
			{
				return this._HinhAnhs;
			}
			set
			{
				this._HinhAnhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_NhanXet", Storage="_NhanXets", ThisKey="MaXe", OtherKey="MaXe")]
		public EntitySet<NhanXet> NhanXets
		{
			get
			{
				return this._NhanXets;
			}
			set
			{
				this._NhanXets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangXe_Xe", Storage="_HangXe", ThisKey="MaNSX", OtherKey="MaNSX", IsForeignKey=true)]
		public HangXe HangXe
		{
			get
			{
				return this._HangXe.Entity;
			}
			set
			{
				HangXe previousValue = this._HangXe.Entity;
				if (((previousValue != value) 
							|| (this._HangXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangXe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._HangXe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._MaNSX = value.MaNSX;
					}
					else
					{
						this._MaNSX = default(string);
					}
					this.SendPropertyChanged("HangXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiXe_Xe", Storage="_LoaiXe", ThisKey="MaLoaiXe", OtherKey="MaLoaiXe", IsForeignKey=true)]
		public LoaiXe LoaiXe
		{
			get
			{
				return this._LoaiXe.Entity;
			}
			set
			{
				LoaiXe previousValue = this._LoaiXe.Entity;
				if (((previousValue != value) 
							|| (this._LoaiXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiXe.Entity = null;
						previousValue.Xes.Remove(this);
					}
					this._LoaiXe.Entity = value;
					if ((value != null))
					{
						value.Xes.Add(this);
						this._MaLoaiXe = value.MaLoaiXe;
					}
					else
					{
						this._MaLoaiXe = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuBans(ChiTietPhieuBan entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_ChiTietPhieuBans(ChiTietPhieuBan entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
		
		private void attach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
		
		private void attach_NhanXets(NhanXet entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_NhanXets(NhanXet entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuBan")]
	public partial class ChiTietPhieuBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_ChiTietPhieuBan;
		
		private int _id_PhieuBan;
		
		private string _MaXe;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<double> _DonGia;
		
		private System.Nullable<double> _ThanhTien;
		
		private EntityRef<Xe> _Xe;
		
		private EntityRef<PhieuBanHang> _PhieuBanHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ChiTietPhieuBanChanging(int value);
    partial void Onid_ChiTietPhieuBanChanged();
    partial void Onid_PhieuBanChanging(int value);
    partial void Onid_PhieuBanChanged();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    partial void OnThanhTienChanging(System.Nullable<double> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public ChiTietPhieuBan()
		{
			this._Xe = default(EntityRef<Xe>);
			this._PhieuBanHang = default(EntityRef<PhieuBanHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ChiTietPhieuBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_ChiTietPhieuBan
		{
			get
			{
				return this._id_ChiTietPhieuBan;
			}
			set
			{
				if ((this._id_ChiTietPhieuBan != value))
				{
					this.Onid_ChiTietPhieuBanChanging(value);
					this.SendPropertyChanging();
					this._id_ChiTietPhieuBan = value;
					this.SendPropertyChanged("id_ChiTietPhieuBan");
					this.Onid_ChiTietPhieuBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_PhieuBan", DbType="Int NOT NULL")]
		public int id_PhieuBan
		{
			get
			{
				return this._id_PhieuBan;
			}
			set
			{
				if ((this._id_PhieuBan != value))
				{
					if (this._PhieuBanHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_PhieuBanChanging(value);
					this.SendPropertyChanging();
					this._id_PhieuBan = value;
					this.SendPropertyChanged("id_PhieuBan");
					this.Onid_PhieuBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="VarChar(5)")]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_ChiTietPhieuBan", Storage="_Xe", ThisKey="MaXe", OtherKey="MaXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.ChiTietPhieuBans.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuBans.Add(this);
						this._MaXe = value.MaXe;
					}
					else
					{
						this._MaXe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuBanHang_ChiTietPhieuBan", Storage="_PhieuBanHang", ThisKey="id_PhieuBan", OtherKey="id_PhieuBan", IsForeignKey=true)]
		public PhieuBanHang PhieuBanHang
		{
			get
			{
				return this._PhieuBanHang.Entity;
			}
			set
			{
				PhieuBanHang previousValue = this._PhieuBanHang.Entity;
				if (((previousValue != value) 
							|| (this._PhieuBanHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuBanHang.Entity = null;
						previousValue.ChiTietPhieuBans.Remove(this);
					}
					this._PhieuBanHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuBans.Add(this);
						this._id_PhieuBan = value.id_PhieuBan;
					}
					else
					{
						this._id_PhieuBan = default(int);
					}
					this.SendPropertyChanged("PhieuBanHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietXe")]
	public partial class ChiTietXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_ChiTietXe;
		
		private string _MucTieuThuNhienLieu;
		
		private string _HopSo;
		
		private string _LoaiTruyenDong;
		
		private string _MoMentCucDai;
		
		private string _DungTichXiLanh;
		
		private string _KhoiLuong;
		
		private string _ChieuDai;
		
		private string _CheuRong;
		
		private string _ChieuCao;
		
		private string _KhoangCachHaiTrucBanh;
		
		private string _DoCaoYen;
		
		private string _KhoangSangGam;
		
		private string _DungTichBinhXang;
		
		private string _KichThuocLopTruoc;
		
		private string _KichThuocLopSau;
		
		private string _CongSuatToiDa;
		
		private string _PhuocTruoc;
		
		private string _PhuocSau;
		
		private string _DungTichNhotMay;
		
		private string _LoaiDongCo;
		
		private EntityRef<Xe> _Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_ChiTietXeChanging(string value);
    partial void Onid_ChiTietXeChanged();
    partial void OnMucTieuThuNhienLieuChanging(string value);
    partial void OnMucTieuThuNhienLieuChanged();
    partial void OnHopSoChanging(string value);
    partial void OnHopSoChanged();
    partial void OnLoaiTruyenDongChanging(string value);
    partial void OnLoaiTruyenDongChanged();
    partial void OnMoMentCucDaiChanging(string value);
    partial void OnMoMentCucDaiChanged();
    partial void OnDungTichXiLanhChanging(string value);
    partial void OnDungTichXiLanhChanged();
    partial void OnKhoiLuongChanging(string value);
    partial void OnKhoiLuongChanged();
    partial void OnChieuDaiChanging(string value);
    partial void OnChieuDaiChanged();
    partial void OnCheuRongChanging(string value);
    partial void OnCheuRongChanged();
    partial void OnChieuCaoChanging(string value);
    partial void OnChieuCaoChanged();
    partial void OnKhoangCachHaiTrucBanhChanging(string value);
    partial void OnKhoangCachHaiTrucBanhChanged();
    partial void OnDoCaoYenChanging(string value);
    partial void OnDoCaoYenChanged();
    partial void OnKhoangSangGamChanging(string value);
    partial void OnKhoangSangGamChanged();
    partial void OnDungTichBinhXangChanging(string value);
    partial void OnDungTichBinhXangChanged();
    partial void OnKichThuocLopTruocChanging(string value);
    partial void OnKichThuocLopTruocChanged();
    partial void OnKichThuocLopSauChanging(string value);
    partial void OnKichThuocLopSauChanged();
    partial void OnCongSuatToiDaChanging(string value);
    partial void OnCongSuatToiDaChanged();
    partial void OnPhuocTruocChanging(string value);
    partial void OnPhuocTruocChanged();
    partial void OnPhuocSauChanging(string value);
    partial void OnPhuocSauChanged();
    partial void OnDungTichNhotMayChanging(string value);
    partial void OnDungTichNhotMayChanged();
    partial void OnLoaiDongCoChanging(string value);
    partial void OnLoaiDongCoChanged();
    #endregion
		
		public ChiTietXe()
		{
			this._Xe = default(EntityRef<Xe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ChiTietXe", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_ChiTietXe
		{
			get
			{
				return this._id_ChiTietXe;
			}
			set
			{
				if ((this._id_ChiTietXe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ChiTietXeChanging(value);
					this.SendPropertyChanging();
					this._id_ChiTietXe = value;
					this.SendPropertyChanged("id_ChiTietXe");
					this.Onid_ChiTietXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucTieuThuNhienLieu", DbType="NVarChar(100)")]
		public string MucTieuThuNhienLieu
		{
			get
			{
				return this._MucTieuThuNhienLieu;
			}
			set
			{
				if ((this._MucTieuThuNhienLieu != value))
				{
					this.OnMucTieuThuNhienLieuChanging(value);
					this.SendPropertyChanging();
					this._MucTieuThuNhienLieu = value;
					this.SendPropertyChanged("MucTieuThuNhienLieu");
					this.OnMucTieuThuNhienLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HopSo", DbType="NVarChar(100)")]
		public string HopSo
		{
			get
			{
				return this._HopSo;
			}
			set
			{
				if ((this._HopSo != value))
				{
					this.OnHopSoChanging(value);
					this.SendPropertyChanging();
					this._HopSo = value;
					this.SendPropertyChanged("HopSo");
					this.OnHopSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTruyenDong", DbType="NVarChar(200)")]
		public string LoaiTruyenDong
		{
			get
			{
				return this._LoaiTruyenDong;
			}
			set
			{
				if ((this._LoaiTruyenDong != value))
				{
					this.OnLoaiTruyenDongChanging(value);
					this.SendPropertyChanging();
					this._LoaiTruyenDong = value;
					this.SendPropertyChanged("LoaiTruyenDong");
					this.OnLoaiTruyenDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoMentCucDai", DbType="NVarChar(200)")]
		public string MoMentCucDai
		{
			get
			{
				return this._MoMentCucDai;
			}
			set
			{
				if ((this._MoMentCucDai != value))
				{
					this.OnMoMentCucDaiChanging(value);
					this.SendPropertyChanging();
					this._MoMentCucDai = value;
					this.SendPropertyChanged("MoMentCucDai");
					this.OnMoMentCucDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungTichXiLanh", DbType="NVarChar(200)")]
		public string DungTichXiLanh
		{
			get
			{
				return this._DungTichXiLanh;
			}
			set
			{
				if ((this._DungTichXiLanh != value))
				{
					this.OnDungTichXiLanhChanging(value);
					this.SendPropertyChanging();
					this._DungTichXiLanh = value;
					this.SendPropertyChanged("DungTichXiLanh");
					this.OnDungTichXiLanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiLuong", DbType="NVarChar(200)")]
		public string KhoiLuong
		{
			get
			{
				return this._KhoiLuong;
			}
			set
			{
				if ((this._KhoiLuong != value))
				{
					this.OnKhoiLuongChanging(value);
					this.SendPropertyChanging();
					this._KhoiLuong = value;
					this.SendPropertyChanged("KhoiLuong");
					this.OnKhoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuDai", DbType="NVarChar(200)")]
		public string ChieuDai
		{
			get
			{
				return this._ChieuDai;
			}
			set
			{
				if ((this._ChieuDai != value))
				{
					this.OnChieuDaiChanging(value);
					this.SendPropertyChanging();
					this._ChieuDai = value;
					this.SendPropertyChanged("ChieuDai");
					this.OnChieuDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheuRong", DbType="NVarChar(200)")]
		public string CheuRong
		{
			get
			{
				return this._CheuRong;
			}
			set
			{
				if ((this._CheuRong != value))
				{
					this.OnCheuRongChanging(value);
					this.SendPropertyChanging();
					this._CheuRong = value;
					this.SendPropertyChanged("CheuRong");
					this.OnCheuRongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChieuCao", DbType="NVarChar(200)")]
		public string ChieuCao
		{
			get
			{
				return this._ChieuCao;
			}
			set
			{
				if ((this._ChieuCao != value))
				{
					this.OnChieuCaoChanging(value);
					this.SendPropertyChanging();
					this._ChieuCao = value;
					this.SendPropertyChanged("ChieuCao");
					this.OnChieuCaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoangCachHaiTrucBanh", DbType="NVarChar(200)")]
		public string KhoangCachHaiTrucBanh
		{
			get
			{
				return this._KhoangCachHaiTrucBanh;
			}
			set
			{
				if ((this._KhoangCachHaiTrucBanh != value))
				{
					this.OnKhoangCachHaiTrucBanhChanging(value);
					this.SendPropertyChanging();
					this._KhoangCachHaiTrucBanh = value;
					this.SendPropertyChanged("KhoangCachHaiTrucBanh");
					this.OnKhoangCachHaiTrucBanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoCaoYen", DbType="NVarChar(200)")]
		public string DoCaoYen
		{
			get
			{
				return this._DoCaoYen;
			}
			set
			{
				if ((this._DoCaoYen != value))
				{
					this.OnDoCaoYenChanging(value);
					this.SendPropertyChanging();
					this._DoCaoYen = value;
					this.SendPropertyChanged("DoCaoYen");
					this.OnDoCaoYenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoangSangGam", DbType="NVarChar(200)")]
		public string KhoangSangGam
		{
			get
			{
				return this._KhoangSangGam;
			}
			set
			{
				if ((this._KhoangSangGam != value))
				{
					this.OnKhoangSangGamChanging(value);
					this.SendPropertyChanging();
					this._KhoangSangGam = value;
					this.SendPropertyChanged("KhoangSangGam");
					this.OnKhoangSangGamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungTichBinhXang", DbType="NVarChar(200)")]
		public string DungTichBinhXang
		{
			get
			{
				return this._DungTichBinhXang;
			}
			set
			{
				if ((this._DungTichBinhXang != value))
				{
					this.OnDungTichBinhXangChanging(value);
					this.SendPropertyChanging();
					this._DungTichBinhXang = value;
					this.SendPropertyChanged("DungTichBinhXang");
					this.OnDungTichBinhXangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuocLopTruoc", DbType="NVarChar(200)")]
		public string KichThuocLopTruoc
		{
			get
			{
				return this._KichThuocLopTruoc;
			}
			set
			{
				if ((this._KichThuocLopTruoc != value))
				{
					this.OnKichThuocLopTruocChanging(value);
					this.SendPropertyChanging();
					this._KichThuocLopTruoc = value;
					this.SendPropertyChanged("KichThuocLopTruoc");
					this.OnKichThuocLopTruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuocLopSau", DbType="NVarChar(200)")]
		public string KichThuocLopSau
		{
			get
			{
				return this._KichThuocLopSau;
			}
			set
			{
				if ((this._KichThuocLopSau != value))
				{
					this.OnKichThuocLopSauChanging(value);
					this.SendPropertyChanging();
					this._KichThuocLopSau = value;
					this.SendPropertyChanged("KichThuocLopSau");
					this.OnKichThuocLopSauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongSuatToiDa", DbType="NVarChar(200)")]
		public string CongSuatToiDa
		{
			get
			{
				return this._CongSuatToiDa;
			}
			set
			{
				if ((this._CongSuatToiDa != value))
				{
					this.OnCongSuatToiDaChanging(value);
					this.SendPropertyChanging();
					this._CongSuatToiDa = value;
					this.SendPropertyChanged("CongSuatToiDa");
					this.OnCongSuatToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuocTruoc", DbType="NVarChar(200)")]
		public string PhuocTruoc
		{
			get
			{
				return this._PhuocTruoc;
			}
			set
			{
				if ((this._PhuocTruoc != value))
				{
					this.OnPhuocTruocChanging(value);
					this.SendPropertyChanging();
					this._PhuocTruoc = value;
					this.SendPropertyChanged("PhuocTruoc");
					this.OnPhuocTruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuocSau", DbType="NVarChar(200)")]
		public string PhuocSau
		{
			get
			{
				return this._PhuocSau;
			}
			set
			{
				if ((this._PhuocSau != value))
				{
					this.OnPhuocSauChanging(value);
					this.SendPropertyChanging();
					this._PhuocSau = value;
					this.SendPropertyChanged("PhuocSau");
					this.OnPhuocSauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DungTichNhotMay", DbType="NVarChar(200)")]
		public string DungTichNhotMay
		{
			get
			{
				return this._DungTichNhotMay;
			}
			set
			{
				if ((this._DungTichNhotMay != value))
				{
					this.OnDungTichNhotMayChanging(value);
					this.SendPropertyChanging();
					this._DungTichNhotMay = value;
					this.SendPropertyChanged("DungTichNhotMay");
					this.OnDungTichNhotMayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDongCo", DbType="NVarChar(200)")]
		public string LoaiDongCo
		{
			get
			{
				return this._LoaiDongCo;
			}
			set
			{
				if ((this._LoaiDongCo != value))
				{
					this.OnLoaiDongCoChanging(value);
					this.SendPropertyChanging();
					this._LoaiDongCo = value;
					this.SendPropertyChanged("LoaiDongCo");
					this.OnLoaiDongCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_ChiTietXe", Storage="_Xe", ThisKey="id_ChiTietXe", OtherKey="MaXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.ChiTietXe = null;
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.ChiTietXe = this;
						this._id_ChiTietXe = value.MaXe;
					}
					else
					{
						this._id_ChiTietXe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangXe")]
	public partial class HangXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNSX;
		
		private string _TenNSX;
		
		private string _AnhBia;
		
		private EntitySet<Xe> _Xes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNSXChanging(string value);
    partial void OnMaNSXChanged();
    partial void OnTenNSXChanging(string value);
    partial void OnTenNSXChanged();
    partial void OnAnhBiaChanging(string value);
    partial void OnAnhBiaChanged();
    #endregion
		
		public HangXe()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNSX", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNSX
		{
			get
			{
				return this._MaNSX;
			}
			set
			{
				if ((this._MaNSX != value))
				{
					this.OnMaNSXChanging(value);
					this.SendPropertyChanging();
					this._MaNSX = value;
					this.SendPropertyChanged("MaNSX");
					this.OnMaNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNSX", DbType="NVarChar(30)")]
		public string TenNSX
		{
			get
			{
				return this._TenNSX;
			}
			set
			{
				if ((this._TenNSX != value))
				{
					this.OnTenNSXChanging(value);
					this.SendPropertyChanging();
					this._TenNSX = value;
					this.SendPropertyChanged("TenNSX");
					this.OnTenNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBia", DbType="VarChar(30)")]
		public string AnhBia
		{
			get
			{
				return this._AnhBia;
			}
			set
			{
				if ((this._AnhBia != value))
				{
					this.OnAnhBiaChanging(value);
					this.SendPropertyChanging();
					this._AnhBia = value;
					this.SendPropertyChanged("AnhBia");
					this.OnAnhBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangXe_Xe", Storage="_Xes", ThisKey="MaNSX", OtherKey="MaNSX")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.HangXe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.HangXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HinhAnh")]
	public partial class HinhAnh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHinh;
		
		private string _Id_DanhMucHinh;
		
		private string _MaLoaiHinh;
		
		private string _TenHinh;
		
		private EntityRef<Xe> _Xe;
		
		private EntityRef<LoaiHinhAnh> _LoaiHinhAnh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHinhChanging(int value);
    partial void OnMaHinhChanged();
    partial void OnId_DanhMucHinhChanging(string value);
    partial void OnId_DanhMucHinhChanged();
    partial void OnMaLoaiHinhChanging(string value);
    partial void OnMaLoaiHinhChanged();
    partial void OnTenHinhChanging(string value);
    partial void OnTenHinhChanged();
    #endregion
		
		public HinhAnh()
		{
			this._Xe = default(EntityRef<Xe>);
			this._LoaiHinhAnh = default(EntityRef<LoaiHinhAnh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHinh
		{
			get
			{
				return this._MaHinh;
			}
			set
			{
				if ((this._MaHinh != value))
				{
					this.OnMaHinhChanging(value);
					this.SendPropertyChanging();
					this._MaHinh = value;
					this.SendPropertyChanged("MaHinh");
					this.OnMaHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DanhMucHinh", DbType="VarChar(5)")]
		public string Id_DanhMucHinh
		{
			get
			{
				return this._Id_DanhMucHinh;
			}
			set
			{
				if ((this._Id_DanhMucHinh != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_DanhMucHinhChanging(value);
					this.SendPropertyChanging();
					this._Id_DanhMucHinh = value;
					this.SendPropertyChanged("Id_DanhMucHinh");
					this.OnId_DanhMucHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHinh", DbType="VarChar(10)")]
		public string MaLoaiHinh
		{
			get
			{
				return this._MaLoaiHinh;
			}
			set
			{
				if ((this._MaLoaiHinh != value))
				{
					if (this._LoaiHinhAnh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiHinhChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHinh = value;
					this.SendPropertyChanged("MaLoaiHinh");
					this.OnMaLoaiHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHinh", DbType="NVarChar(30)")]
		public string TenHinh
		{
			get
			{
				return this._TenHinh;
			}
			set
			{
				if ((this._TenHinh != value))
				{
					this.OnTenHinhChanging(value);
					this.SendPropertyChanging();
					this._TenHinh = value;
					this.SendPropertyChanged("TenHinh");
					this.OnTenHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_HinhAnh", Storage="_Xe", ThisKey="Id_DanhMucHinh", OtherKey="MaXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.HinhAnhs.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.HinhAnhs.Add(this);
						this._Id_DanhMucHinh = value.MaXe;
					}
					else
					{
						this._Id_DanhMucHinh = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHinhAnh_HinhAnh", Storage="_LoaiHinhAnh", ThisKey="MaLoaiHinh", OtherKey="MaLoaiHinh", IsForeignKey=true)]
		public LoaiHinhAnh LoaiHinhAnh
		{
			get
			{
				return this._LoaiHinhAnh.Entity;
			}
			set
			{
				LoaiHinhAnh previousValue = this._LoaiHinhAnh.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHinhAnh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHinhAnh.Entity = null;
						previousValue.HinhAnhs.Remove(this);
					}
					this._LoaiHinhAnh.Entity = value;
					if ((value != null))
					{
						value.HinhAnhs.Add(this);
						this._MaLoaiHinh = value.MaLoaiHinh;
					}
					else
					{
						this._MaLoaiHinh = default(string);
					}
					this.SendPropertyChanged("LoaiHinhAnh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HinhThucThanhToan")]
	public partial class HinhThucThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHinhThuc;
		
		private string _TenHinhThuc;
		
		private EntitySet<PhieuBanHang> _PhieuBanHangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHinhThucChanging(int value);
    partial void OnMaHinhThucChanged();
    partial void OnTenHinhThucChanging(string value);
    partial void OnTenHinhThucChanged();
    #endregion
		
		public HinhThucThanhToan()
		{
			this._PhieuBanHangs = new EntitySet<PhieuBanHang>(new Action<PhieuBanHang>(this.attach_PhieuBanHangs), new Action<PhieuBanHang>(this.detach_PhieuBanHangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHinhThuc
		{
			get
			{
				return this._MaHinhThuc;
			}
			set
			{
				if ((this._MaHinhThuc != value))
				{
					this.OnMaHinhThucChanging(value);
					this.SendPropertyChanging();
					this._MaHinhThuc = value;
					this.SendPropertyChanged("MaHinhThuc");
					this.OnMaHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHinhThuc", DbType="NVarChar(40)")]
		public string TenHinhThuc
		{
			get
			{
				return this._TenHinhThuc;
			}
			set
			{
				if ((this._TenHinhThuc != value))
				{
					this.OnTenHinhThucChanging(value);
					this.SendPropertyChanging();
					this._TenHinhThuc = value;
					this.SendPropertyChanged("TenHinhThuc");
					this.OnTenHinhThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HinhThucThanhToan_PhieuBanHang", Storage="_PhieuBanHangs", ThisKey="MaHinhThuc", OtherKey="HT_ThanhToan")]
		public EntitySet<PhieuBanHang> PhieuBanHangs
		{
			get
			{
				return this._PhieuBanHangs;
			}
			set
			{
				this._PhieuBanHangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuBanHangs(PhieuBanHang entity)
		{
			this.SendPropertyChanging();
			entity.HinhThucThanhToan = this;
		}
		
		private void detach_PhieuBanHangs(PhieuBanHang entity)
		{
			this.SendPropertyChanging();
			entity.HinhThucThanhToan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private string _TenDangNhap;
		
		private string _TenKhach;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _HinhAnh;
		
		private System.Nullable<int> _SoLuotMua;
		
		private EntityRef<KhachHangThanThiet> _KhachHangThanThiet;
		
		private EntitySet<PhieuBanHang> _PhieuBanHangs;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnTenKhachChanging(string value);
    partial void OnTenKhachChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnSoLuotMuaChanging(System.Nullable<int> value);
    partial void OnSoLuotMuaChanged();
    #endregion
		
		public KhachHang()
		{
			this._KhachHangThanThiet = default(EntityRef<KhachHangThanThiet>);
			this._PhieuBanHangs = new EntitySet<PhieuBanHang>(new Action<PhieuBanHang>(this.attach_PhieuBanHangs), new Action<PhieuBanHang>(this.detach_PhieuBanHangs));
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhach", DbType="NVarChar(50)")]
		public string TenKhach
		{
			get
			{
				return this._TenKhach;
			}
			set
			{
				if ((this._TenKhach != value))
				{
					this.OnTenKhachChanging(value);
					this.SendPropertyChanging();
					this._TenKhach = value;
					this.SendPropertyChanged("TenKhach");
					this.OnTenKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(30)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuotMua", DbType="Int")]
		public System.Nullable<int> SoLuotMua
		{
			get
			{
				return this._SoLuotMua;
			}
			set
			{
				if ((this._SoLuotMua != value))
				{
					this.OnSoLuotMuaChanging(value);
					this.SendPropertyChanging();
					this._SoLuotMua = value;
					this.SendPropertyChanged("SoLuotMua");
					this.OnSoLuotMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_KhachHangThanThiet", Storage="_KhachHangThanThiet", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsUnique=true, IsForeignKey=false)]
		public KhachHangThanThiet KhachHangThanThiet
		{
			get
			{
				return this._KhachHangThanThiet.Entity;
			}
			set
			{
				KhachHangThanThiet previousValue = this._KhachHangThanThiet.Entity;
				if (((previousValue != value) 
							|| (this._KhachHangThanThiet.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHangThanThiet.Entity = null;
						previousValue.KhachHang = null;
					}
					this._KhachHangThanThiet.Entity = value;
					if ((value != null))
					{
						value.KhachHang = this;
					}
					this.SendPropertyChanged("KhachHangThanThiet");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuBanHang", Storage="_PhieuBanHangs", ThisKey="MaKhachHang", OtherKey="MaKhachHang")]
		public EntitySet<PhieuBanHang> PhieuBanHangs
		{
			get
			{
				return this._PhieuBanHangs;
			}
			set
			{
				this._PhieuBanHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_KhachHang", Storage="_Account", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.KhachHangs.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.KhachHangs.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuBanHangs(PhieuBanHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_PhieuBanHangs(PhieuBanHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHangThanThiet")]
	public partial class KhachHangThanThiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private System.Nullable<int> _LoaiKhach;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<LoaiKhachHang> _LoaiKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnLoaiKhachChanging(System.Nullable<int> value);
    partial void OnLoaiKhachChanged();
    #endregion
		
		public KhachHangThanThiet()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._LoaiKhachHang = default(EntityRef<LoaiKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhach", DbType="Int")]
		public System.Nullable<int> LoaiKhach
		{
			get
			{
				return this._LoaiKhach;
			}
			set
			{
				if ((this._LoaiKhach != value))
				{
					if (this._LoaiKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiKhachChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhach = value;
					this.SendPropertyChanged("LoaiKhach");
					this.OnLoaiKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_KhachHangThanThiet", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.KhachHangThanThiet = null;
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.KhachHangThanThiet = this;
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiKhachHang_KhachHangThanThiet", Storage="_LoaiKhachHang", ThisKey="LoaiKhach", OtherKey="LoaiKhach", IsForeignKey=true)]
		public LoaiKhachHang LoaiKhachHang
		{
			get
			{
				return this._LoaiKhachHang.Entity;
			}
			set
			{
				LoaiKhachHang previousValue = this._LoaiKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._LoaiKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiKhachHang.Entity = null;
						previousValue.KhachHangThanThiets.Remove(this);
					}
					this._LoaiKhachHang.Entity = value;
					if ((value != null))
					{
						value.KhachHangThanThiets.Add(this);
						this._LoaiKhach = value.LoaiKhach;
					}
					else
					{
						this._LoaiKhach = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiAcc")]
	public partial class LoaiAcc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _TenLoaiAcc;
		
		private EntitySet<Account> _Accounts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnTenLoaiAccChanging(string value);
    partial void OnTenLoaiAccChanged();
    #endregion
		
		public LoaiAcc()
		{
			this._Accounts = new EntitySet<Account>(new Action<Account>(this.attach_Accounts), new Action<Account>(this.detach_Accounts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiAcc", DbType="NVarChar(30)")]
		public string TenLoaiAcc
		{
			get
			{
				return this._TenLoaiAcc;
			}
			set
			{
				if ((this._TenLoaiAcc != value))
				{
					this.OnTenLoaiAccChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiAcc = value;
					this.SendPropertyChanged("TenLoaiAcc");
					this.OnTenLoaiAccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiAcc_Account", Storage="_Accounts", ThisKey="id", OtherKey="LoaiAcc")]
		public EntitySet<Account> Accounts
		{
			get
			{
				return this._Accounts;
			}
			set
			{
				this._Accounts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Accounts(Account entity)
		{
			this.SendPropertyChanging();
			entity.LoaiAcc1 = this;
		}
		
		private void detach_Accounts(Account entity)
		{
			this.SendPropertyChanging();
			entity.LoaiAcc1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiHinhAnh")]
	public partial class LoaiHinhAnh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiHinh;
		
		private string _TenLoaiHinh;
		
		private EntitySet<HinhAnh> _HinhAnhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiHinhChanging(string value);
    partial void OnMaLoaiHinhChanged();
    partial void OnTenLoaiHinhChanging(string value);
    partial void OnTenLoaiHinhChanged();
    #endregion
		
		public LoaiHinhAnh()
		{
			this._HinhAnhs = new EntitySet<HinhAnh>(new Action<HinhAnh>(this.attach_HinhAnhs), new Action<HinhAnh>(this.detach_HinhAnhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHinh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiHinh
		{
			get
			{
				return this._MaLoaiHinh;
			}
			set
			{
				if ((this._MaLoaiHinh != value))
				{
					this.OnMaLoaiHinhChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHinh = value;
					this.SendPropertyChanged("MaLoaiHinh");
					this.OnMaLoaiHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiHinh", DbType="NVarChar(30)")]
		public string TenLoaiHinh
		{
			get
			{
				return this._TenLoaiHinh;
			}
			set
			{
				if ((this._TenLoaiHinh != value))
				{
					this.OnTenLoaiHinhChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiHinh = value;
					this.SendPropertyChanged("TenLoaiHinh");
					this.OnTenLoaiHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHinhAnh_HinhAnh", Storage="_HinhAnhs", ThisKey="MaLoaiHinh", OtherKey="MaLoaiHinh")]
		public EntitySet<HinhAnh> HinhAnhs
		{
			get
			{
				return this._HinhAnhs;
			}
			set
			{
				this._HinhAnhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHinhAnh = this;
		}
		
		private void detach_HinhAnhs(HinhAnh entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHinhAnh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiKhachHang")]
	public partial class LoaiKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LoaiKhach;
		
		private string _TenLoai;
		
		private System.Nullable<int> _PhanTramUuDai;
		
		private EntitySet<KhachHangThanThiet> _KhachHangThanThiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiKhachChanging(int value);
    partial void OnLoaiKhachChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnPhanTramUuDaiChanging(System.Nullable<int> value);
    partial void OnPhanTramUuDaiChanged();
    #endregion
		
		public LoaiKhachHang()
		{
			this._KhachHangThanThiets = new EntitySet<KhachHangThanThiet>(new Action<KhachHangThanThiet>(this.attach_KhachHangThanThiets), new Action<KhachHangThanThiet>(this.detach_KhachHangThanThiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhach", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LoaiKhach
		{
			get
			{
				return this._LoaiKhach;
			}
			set
			{
				if ((this._LoaiKhach != value))
				{
					this.OnLoaiKhachChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhach = value;
					this.SendPropertyChanged("LoaiKhach");
					this.OnLoaiKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(40)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanTramUuDai", DbType="Int")]
		public System.Nullable<int> PhanTramUuDai
		{
			get
			{
				return this._PhanTramUuDai;
			}
			set
			{
				if ((this._PhanTramUuDai != value))
				{
					this.OnPhanTramUuDaiChanging(value);
					this.SendPropertyChanging();
					this._PhanTramUuDai = value;
					this.SendPropertyChanged("PhanTramUuDai");
					this.OnPhanTramUuDaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiKhachHang_KhachHangThanThiet", Storage="_KhachHangThanThiets", ThisKey="LoaiKhach", OtherKey="LoaiKhach")]
		public EntitySet<KhachHangThanThiet> KhachHangThanThiets
		{
			get
			{
				return this._KhachHangThanThiets;
			}
			set
			{
				this._KhachHangThanThiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhachHangThanThiets(KhachHangThanThiet entity)
		{
			this.SendPropertyChanging();
			entity.LoaiKhachHang = this;
		}
		
		private void detach_KhachHangThanThiets(KhachHangThanThiet entity)
		{
			this.SendPropertyChanging();
			entity.LoaiKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiXe")]
	public partial class LoaiXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiXe;
		
		private string _TenLoaiXe;
		
		private string _Icon;
		
		private EntitySet<Xe> _Xes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiXeChanging(int value);
    partial void OnMaLoaiXeChanged();
    partial void OnTenLoaiXeChanging(string value);
    partial void OnTenLoaiXeChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    #endregion
		
		public LoaiXe()
		{
			this._Xes = new EntitySet<Xe>(new Action<Xe>(this.attach_Xes), new Action<Xe>(this.detach_Xes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiXe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiXe
		{
			get
			{
				return this._MaLoaiXe;
			}
			set
			{
				if ((this._MaLoaiXe != value))
				{
					this.OnMaLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiXe = value;
					this.SendPropertyChanged("MaLoaiXe");
					this.OnMaLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiXe", DbType="NVarChar(50)")]
		public string TenLoaiXe
		{
			get
			{
				return this._TenLoaiXe;
			}
			set
			{
				if ((this._TenLoaiXe != value))
				{
					this.OnTenLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiXe = value;
					this.SendPropertyChanged("TenLoaiXe");
					this.OnTenLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="VarChar(30)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiXe_Xe", Storage="_Xes", ThisKey="MaLoaiXe", OtherKey="MaLoaiXe")]
		public EntitySet<Xe> Xes
		{
			get
			{
				return this._Xes;
			}
			set
			{
				this._Xes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiXe = this;
		}
		
		private void detach_Xes(Xe entity)
		{
			this.SendPropertyChanging();
			entity.LoaiXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhanVien;
		
		private string _TenDangNhap;
		
		private string _TenNhanVien;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntityRef<Account> _Account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public NhanVien()
		{
			this._Account = default(EntityRef<Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(50)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Account_NhanVien", Storage="_Account", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public Account Account
		{
			get
			{
				return this._Account.Entity;
			}
			set
			{
				Account previousValue = this._Account.Entity;
				if (((previousValue != value) 
							|| (this._Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Account.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._Account.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanXet")]
	public partial class NhanXet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nhanXet;
		
		private string _MaXe;
		
		private string _NguoiBinhLuan;
		
		private string _BinhLuan;
		
		private EntityRef<Xe> _Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhanXetChanging(int value);
    partial void Onid_nhanXetChanged();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnNguoiBinhLuanChanging(string value);
    partial void OnNguoiBinhLuanChanged();
    partial void OnBinhLuanChanging(string value);
    partial void OnBinhLuanChanged();
    #endregion
		
		public NhanXet()
		{
			this._Xe = default(EntityRef<Xe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanXet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nhanXet
		{
			get
			{
				return this._id_nhanXet;
			}
			set
			{
				if ((this._id_nhanXet != value))
				{
					this.Onid_nhanXetChanging(value);
					this.SendPropertyChanging();
					this._id_nhanXet = value;
					this.SendPropertyChanged("id_nhanXet");
					this.Onid_nhanXetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="VarChar(5)")]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiBinhLuan", DbType="NVarChar(30)")]
		public string NguoiBinhLuan
		{
			get
			{
				return this._NguoiBinhLuan;
			}
			set
			{
				if ((this._NguoiBinhLuan != value))
				{
					this.OnNguoiBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._NguoiBinhLuan = value;
					this.SendPropertyChanged("NguoiBinhLuan");
					this.OnNguoiBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BinhLuan", DbType="NVarChar(500)")]
		public string BinhLuan
		{
			get
			{
				return this._BinhLuan;
			}
			set
			{
				if ((this._BinhLuan != value))
				{
					this.OnBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._BinhLuan = value;
					this.SendPropertyChanged("BinhLuan");
					this.OnBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_NhanXet", Storage="_Xe", ThisKey="MaXe", OtherKey="MaXe", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.NhanXets.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.NhanXets.Add(this);
						this._MaXe = value.MaXe;
					}
					else
					{
						this._MaXe = default(string);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuBanHang")]
	public partial class PhieuBanHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhachHang;
		
		private System.Nullable<System.DateTime> _NgayBan;
		
		private System.Nullable<long> _ThanhToan;
		
		private int _id_PhieuBan;
		
		private System.Nullable<int> _HT_ThanhToan;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntitySet<ChiTietPhieuBan> _ChiTietPhieuBans;
		
		private EntityRef<HinhThucThanhToan> _HinhThucThanhToan;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhachHangChanging(string value);
    partial void OnMaKhachHangChanged();
    partial void OnNgayBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBanChanged();
    partial void OnThanhToanChanging(System.Nullable<long> value);
    partial void OnThanhToanChanged();
    partial void Onid_PhieuBanChanging(int value);
    partial void Onid_PhieuBanChanged();
    partial void OnHT_ThanhToanChanging(System.Nullable<int> value);
    partial void OnHT_ThanhToanChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public PhieuBanHang()
		{
			this._ChiTietPhieuBans = new EntitySet<ChiTietPhieuBan>(new Action<ChiTietPhieuBan>(this.attach_ChiTietPhieuBans), new Action<ChiTietPhieuBan>(this.detach_ChiTietPhieuBans));
			this._HinhThucThanhToan = default(EntityRef<HinhThucThanhToan>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhachHang", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string MaKhachHang
		{
			get
			{
				return this._MaKhachHang;
			}
			set
			{
				if ((this._MaKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._MaKhachHang = value;
					this.SendPropertyChanged("MaKhachHang");
					this.OnMaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBan
		{
			get
			{
				return this._NgayBan;
			}
			set
			{
				if ((this._NgayBan != value))
				{
					this.OnNgayBanChanging(value);
					this.SendPropertyChanging();
					this._NgayBan = value;
					this.SendPropertyChanged("NgayBan");
					this.OnNgayBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhToan", DbType="BigInt")]
		public System.Nullable<long> ThanhToan
		{
			get
			{
				return this._ThanhToan;
			}
			set
			{
				if ((this._ThanhToan != value))
				{
					this.OnThanhToanChanging(value);
					this.SendPropertyChanging();
					this._ThanhToan = value;
					this.SendPropertyChanged("ThanhToan");
					this.OnThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_PhieuBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_PhieuBan
		{
			get
			{
				return this._id_PhieuBan;
			}
			set
			{
				if ((this._id_PhieuBan != value))
				{
					this.Onid_PhieuBanChanging(value);
					this.SendPropertyChanging();
					this._id_PhieuBan = value;
					this.SendPropertyChanged("id_PhieuBan");
					this.Onid_PhieuBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HT_ThanhToan", DbType="Int")]
		public System.Nullable<int> HT_ThanhToan
		{
			get
			{
				return this._HT_ThanhToan;
			}
			set
			{
				if ((this._HT_ThanhToan != value))
				{
					if (this._HinhThucThanhToan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHT_ThanhToanChanging(value);
					this.SendPropertyChanging();
					this._HT_ThanhToan = value;
					this.SendPropertyChanged("HT_ThanhToan");
					this.OnHT_ThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuBanHang_ChiTietPhieuBan", Storage="_ChiTietPhieuBans", ThisKey="id_PhieuBan", OtherKey="id_PhieuBan")]
		public EntitySet<ChiTietPhieuBan> ChiTietPhieuBans
		{
			get
			{
				return this._ChiTietPhieuBans;
			}
			set
			{
				this._ChiTietPhieuBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HinhThucThanhToan_PhieuBanHang", Storage="_HinhThucThanhToan", ThisKey="HT_ThanhToan", OtherKey="MaHinhThuc", IsForeignKey=true)]
		public HinhThucThanhToan HinhThucThanhToan
		{
			get
			{
				return this._HinhThucThanhToan.Entity;
			}
			set
			{
				HinhThucThanhToan previousValue = this._HinhThucThanhToan.Entity;
				if (((previousValue != value) 
							|| (this._HinhThucThanhToan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HinhThucThanhToan.Entity = null;
						previousValue.PhieuBanHangs.Remove(this);
					}
					this._HinhThucThanhToan.Entity = value;
					if ((value != null))
					{
						value.PhieuBanHangs.Add(this);
						this._HT_ThanhToan = value.MaHinhThuc;
					}
					else
					{
						this._HT_ThanhToan = default(Nullable<int>);
					}
					this.SendPropertyChanged("HinhThucThanhToan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuBanHang", Storage="_KhachHang", ThisKey="MaKhachHang", OtherKey="MaKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.PhieuBanHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.PhieuBanHangs.Add(this);
						this._MaKhachHang = value.MaKhachHang;
					}
					else
					{
						this._MaKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuBans(ChiTietPhieuBan entity)
		{
			this.SendPropertyChanging();
			entity.PhieuBanHang = this;
		}
		
		private void detach_ChiTietPhieuBans(ChiTietPhieuBan entity)
		{
			this.SendPropertyChanging();
			entity.PhieuBanHang = null;
		}
	}
}
#pragma warning restore 1591
